//************FOR EASE OF USE, BOTH task.js AND taskPage.js TESTING WILL BE DONE HERE************

//TESTING FOR REMINDER FUNCTIONS IN task.js

//TESTING FOR TASK FUNCTIONS IN task.js

//TESTING FOR CHANGE TASK AND MODIFY FUNCTIONS IN taskPage.js

//TESTING FOR ADD AND REMOVE FUNCTIONS